### ISSUE TITLE
代码注释错误

### ISSUE THREAD

**Issue by lrsgzs** [Smart-Space/tkwebview2#1]
# tkwebview2.py

**Comment by Smart-Space** [comment]
已更改，感谢反馈

**Comment by TotoWang-hhh** [comment]
> # tkwebview2.py
> ## 102行，注释“#检测是否含义webview2 runtime"中，”含义“应该是”存在“

可能是指“含有”吧，还没改过来，哈哈

**Comment by Smart-Space** [comment]
意外意外，之前改了，一波操作给整没了。。。
