### ISSUE TITLE
Need Update

### ISSUE THREAD

**Issue by ialak** [Smart-Space/tkwebview2#14]
https://github.com/Smart-Space/tkwebview2/blob/85ba328cf4e2449182143d1ba053f8a27ea85922/tkwebview2.py#L36
To self.web_view.webview

**Comment by Smart-Space** [comment]
Thanks for the feedback. The latest tkwebview2 will check the class EdgeChrome for its attribute "webview" or "web_view".

PLUS, this project is probably no longer maintained, you can try other projects, like [webviewpy](https://github.com/HIllya51/webviewpy).
