### ISSUE TITLE
选中文本的问题

### ISSUE THREAD

**Issue by TotoWang-hhh** [Smart-Space/tkwebview2#2]
我原本以为重写tkwebview2导致以后无法选择网页文本，现在看来是您故意的啊
![图片](https://user-images.githubusercontent.com/67090055/210138136-86339857-3368-48db-b806-0b024e615620.png)

以及注释有错别字：
![图片](https://user-images.githubusercontent.com/67090055/210138157-5eae462f-81e0-45ea-9ce0-44b2a395dd56.png)

**Comment by TotoWang-hhh** [comment]
包括下载文件和右键菜单现在都没了，不知道以后还能否加回来

**Comment by Smart-Space** [comment]
文字可选、菜单、开发者工具都加上了。

下载文件是什么意思？

**Comment by TotoWang-hhh** [comment]
> 文字可选、菜单、开发者工具都加上了。
> 
> 下载文件是什么意思？

以前的版本里，如果点击某个下载链接，Webview2的角落里会弹出下载的框，问你是打开还是下载（另存为），就跟在Edge里一样

**Comment by Smart-Space** [comment]
以前版本有吗？我没印象，如果你知道的话可以告诉我是哪个版本之前。

我看webview2的文档好像没有这个功能，浏览器的指定另存为应该是微软edge团队自己写的。

**Comment by TotoWang-hhh** [comment]
> 以前版本有吗？我没印象，如果你知道的话可以告诉我是哪个版本之前。
> 
> 我看webview2的文档好像没有这个功能，浏览器的指定另存为应该是微软edge团队自己写的。

下载、另存为等就是Edge的功能，不过以前会显示在tkwebview2里，现在似乎没有显示出来

**Comment by Smart-Space** [comment]
我重新在pypi上下载了tkwebview2的初期几个版本，下载功能都是直接下载。如果是webview2自己的内置功能那我也无能为力，不过看了文档好像是可以接管DownloadStarting事件，我可能考虑写一个能够另存为的事件。当然，仅供参考。

**Comment by Smart-Space** [comment]
这个issue到这结束，关于下载功能看情况。

**Comment by TotoWang-hhh** [comment]
> 我重新在pypi上下载了tkwebview2的初期几个版本，下载功能都是直接下载。如果是webview2自己的内置功能那我也无能为力，不过看了文档好像是可以接管DownloadStarting事件，我可能考虑写一个能够另存为的事件。当然，仅供参考。

直接下载和另存为可能跟Edge设置有关把

**Comment by TotoWang-hhh** [comment]
> > 我重新在pypi上下载了tkwebview2的初期几个版本，下载功能都是直接下载。如果是webview2自己的内置功能那我也无能为力，不过看了文档好像是可以接管DownloadStarting事件，我可能考虑写一个能够另存为的事件。当然，仅供参考。
> 
> 直接下载和另存为可能跟Edge设置有关把

我的Edge以前设置的是每次都询问我做什么，下载到哪里（默认是直接下）
后来把Edge强行卸了
👆应该没啥关系吧

**Comment by Smart-Space** [comment]
Edge浏览器是这样，但是WebView2控件就是直接下载。我也没找到相关资料。

**Comment by TotoWang-hhh** [comment]
> Edge浏览器是这样，但是WebView2控件就是直接下载。我也没找到相关资料。

可惜当时没截图，感觉以前的tkwebview2就相当于砍头（指地址栏等）的Edge😂

**Comment by Smart-Space** [comment]
“无可考证”😂，虽然我只想把tkwebview2仅当作显示网页的控件来写，WebView2Core是直接提供给编写者自己来写的
