### ISSUE TITLE
小插曲1

### ISSUE THREAD

**Issue by TotoWang-hhh** [Smart-Space/tkwebview2#5]
这个计时可能不准，但是如果是真的，4秒来检测环境！？

传不上截图，等会网好了在回复里传

P.S. 这FastGitHub开了怎么跟没开一样……

**Comment by TotoWang-hhh** [comment]
![图片](https://user-images.githubusercontent.com/67090055/210962992-a8e7a81a-03d5-4f7b-a485-c7e826d0de72.png)

**Comment by Smart-Space** [comment]
我显示的是0秒。

其实我没仔细看这个文件。

![image](https://user-images.githubusercontent.com/63576822/210963431-9cf68850-35c5-435d-af90-3d30c47710c4.png)

**Comment by TotoWang-hhh** [comment]
> 我显示的是0秒。
> 
> 其实我没仔细看这个文件。
> 
> ![image](https://user-images.githubusercontent.com/63576822/210963431-9cf68850-35c5-435d-af90-3d30c47710c4.png)

az，可能我电脑性能烂，我用的笔记本，现在还没插电源，谅解一下

**Comment by TotoWang-hhh** [comment]
既然问题仅存在于我，那多半是我的问题罢

**Comment by TotoWang-hhh** [comment]
嗯所以我为啥要reopen？

好问题又增加了
