### ISSUE TITLE
请问这个问题应该怎么解决

### ISSUE THREAD

**Issue by adminoryuan** [Smart-Space/tkwebview2#8]
S C:\Users\Administrator\Desktop\broadban\broadband-manager> python .\test.py

未经处理的异常:  Python.Runtime.PythonException: Window.__init__() got an unexpected keyword argument 'zoomable'
   在 Python.Runtime.PythonException.ThrowLastAsClrException()
   在 Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   在 Python.Runtime.Dispatcher.Dispatch(Object[] args)
   在 __System_Threading_ThreadStartDispatcher.Invoke()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
# 这是代码
```python

from tkinter import Tk
from tkwebview2.tkwebview2 import WebView2, have_runtime, install_runtime
import clr


clr.AddReference('System.Windows.Forms')
clr.AddReference('System.Threading')
from System.Windows.Forms import Control
from System.Threading import Thread,ApartmentState,ThreadStart    

#范例
def main():
    if not have_runtime():#没有webview2 runtime
        install_runtime()
    root=Tk()
    root.title('pywebview for tkinter test')
    root.geometry('1200x600+5+5')

    frame=WebView2(root,500,500)
    frame.pack(side='left')
    frame.load_html('<h1>hi hi</h1>')

    frame2=WebView2(root,500,500)
    frame2.pack(side='left',padx=20,fill='both',expand=True)
    frame2.load_url('https://smart-space.com.cn/')

    root.mainloop()

if __name__ == "__main__":
    t = Thread(ThreadStart(main))
    t.ApartmentState = ApartmentState.STA
    t.Start()
    t.Join()```

**Comment by BeetSoup128** [comment]
看看 issue#7. 可以尝试升级pywebview版本到4.0+以解决问题
