### ISSUE TITLE
有没有 Pyqt 的版本？

### ISSUE THREAD

**Issue by iferencz** [Smart-Space/tkwebview2#9]
如题，自己不会写，作者大大可以研究一下吗？蟹蟹

**Comment by Smart-Space** [comment]
抱歉，不行。
1. 我没有精力继续维护这个项目
2. pyqt有自己的html渲染控件，而这是因为tkinter没有这类控件才开发的
3. 据我所知，微软到目前为止并没有公开或开发除了自家三大UI库之外其它直接使用webview2的方法，tkwebview2是通过嵌入WinForm控件实现的
